compile : Assignment2_onebin.c Assignment2_spheap.c test_spheap.c onebin.h spheap.h Assignment2.c
	gcc -o Assignment2_spheap spheap.h Assignment2_spheap.c -lm -w
	gcc -o Assignment2_onebin onebin.h spheap.h Assignment2_onebin.c -lm -w
	gcc -o test_spheap spheap.h test_spheap.c -lm -w
	gcc -o test_onebin onebin.h test_onebin.c -lm -w
	gcc -o Assignment2 Assignment2.c -lm -w